// This file should be auto-generated by the Supabase CLI:
// npx supabase gen types typescript --project-id your-project-id > types/database.ts

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          name: string
          email: string
          username: string
          school: string | null
          canvas_token: string | null
          canvas_domain: string | null
          created_at: string
        }
        Insert: {
          id: string
          name: string
          email: string
          username: string
          school?: string | null
          canvas_token?: string | null
          canvas_domain?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          email?: string
          username?: string
          school?: string | null
          canvas_token?: string | null
          canvas_domain?: string | null
          created_at?: string
        }
        Relationships: []
      }
      login_activity: {
        Row: {
          id: string
          user_id: string
          login_at: string
        }
        Insert: {
          id?: string
          user_id: string
          login_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          login_at?: string
        }
        Relationships: []
      }
      classes: {
        Row: {
          id: string
          user_id: string
          name: string
          start_time: string
          end_time: string
          days: string[]
          room: string
          professor: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          start_time: string
          end_time: string
          days: string[]
          room: string
          professor?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          start_time?: string
          end_time?: string
          days?: string[]
          room?: string
          professor?: string | null
          created_at?: string
        }
        Relationships: []
      }
      tasks: {
        Row: {
          id: string
          user_id: string
          title: string
          date: string
          start_time: string | null
          end_time: string | null
          all_day: boolean
          completed: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          date: string
          start_time?: string | null
          end_time?: string | null
          all_day?: boolean
          completed?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          date?: string
          start_time?: string | null
          end_time?: string | null
          all_day?: boolean
          completed?: boolean
          created_at?: string
        }
        Relationships: []
      }
      spotify_tokens: {
        Row: {
          id: string
          user_id: string
          access_token: string
          refresh_token: string
          expires_at: string
        }
        Insert: {
          id?: string
          user_id: string
          access_token: string
          refresh_token: string
          expires_at: string
        }
        Update: {
          id?: string
          user_id?: string
          access_token?: string
          refresh_token?: string
          expires_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
